var statePerCapita = {
    "frames": [],
    "layout": {
        "title": "GUN DEATH RATE BY STATE (PER 100K) ",
        "geo": {
            "showlakes": true,
            "scope": "usa",
            "lakecolor": "rgb(255, 255, 255)",
            "projection": {
                "scale": 0.8531036134105232,
                "type": "albers usa"
            },
            "center": {
                "lat": 38.254605005933215,
                "lon": -86.96621500419081
            }
        },
        "breakpoints": []
    },
    "data": [
        {
            "reversescale": false,
            "locationssrc": "manuelamachado:10:5c3985",
            "zmax": 23,
            "uid": "93a716",
            "colorscale": [
                [
                    0,
                    "rgb(5, 10, 172)"
                ],
                [
                    0.35,
                    "rgb(106, 137, 247)"
                ],
                [
                    0.5,
                    "rgb(190, 190, 190)"
                ],
                [
                    0.6,
                    "rgb(220, 170, 132)"
                ],
                [
                    0.7,
                    "rgb(230, 145, 90)"
                ],
                [
                    1,
                    "rgb(178, 10, 28)"
                ]
            ],
            "zsrc": "manuelamachado:10:c86748",
            "text": [
                "Illinois",
                "California",
                "Florida",
                "Texas",
                "Ohio",
                "New York",
                "Pennsylvania",
                "Georgia",
                "North Carolina",
                "Louisiana",
                "Tennessee",
                "South Carolina",
                "Missouri",
                "Michigan",
                "Massachusetts",
                "Virginia",
                "Indiana",
                "Maryland",
                "Alabama",
                "New Jersey",
                "Wisconsin",
                "Kentucky",
                "Mississippi",
                "Oklahoma",
                "Washington",
                "Colorado",
                "District of Columbia",
                "Connecticut",
                "Arkansas",
                "Iowa",
                "Minnesota",
                "Arizona",
                "Oregon",
                "Kansas",
                "Nevada",
                "Delaware",
                "Nebraska",
                "New Mexico",
                "West Virginia",
                "Alaska",
                "Utah",
                "New Hampshire",
                "Maine",
                "Rhode Island",
                "Idaho",
                "Montana",
                "North Dakota",
                "South Dakota",
                "Wyoming",
                "Vermont",
                "Hawaii"
            ],
            "zmin": 3.4,
            "locations": [
                "IL",
                "CA",
                "FL",
                "TX",
                "OH",
                "NY",
                "PA",
                "GA",
                "NC",
                "LA",
                "TN",
                "SC",
                "MO",
                "MI",
                "MA",
                "VA",
                "IN",
                "MD",
                "AL",
                "NJ",
                "WI",
                "KY",
                "MS",
                "OK",
                "WA",
                "CO",
                "DC",
                "CT",
                "AR",
                "IA",
                "MN",
                "AZ",
                "OR",
                "KS",
                "NV",
                "DE",
                "NE",
                "NM",
                "WV",
                "AK",
                "UT",
                "NH",
                "ME",
                "RI",
                "ID",
                "MT",
                "ND",
                "SD",
                "WY",
                "VT",
                "HI"
            ],
            "textsrc": "manuelamachado:10:8427ff",
            "autocolorscale": false,
            "colorbar": {
                "y": 0.5,
                "x": 0.9537748344370861,
                "title": "Frequency per capita"
            },
            "showscale": true,
            "marker": {
                "line": {
                    "color": "rgb(255,255,255)",
                    "width": 2
                }
            },
            "locationmode": "USA-states",
            "z": [
                "11.6",
                "7.9",
                "12.6",
                "12.1",
                "12.9",
                "4.4",
                "11.9",
                "14.9",
                "13.6",
                "21.2",
                "17",
                "17.7",
                "18.8",
                "12.2",
                "3.4",
                "12",
                "14.9",
                "11.8",
                "21.4",
                "5.5",
                "11.4",
                "17.5",
                "19.8",
                "19.6",
                "9",
                "14.3",
                "9",
                "4.6",
                "17.7",
                "9.2",
                "7.6",
                "15.2",
                "11.8",
                "13.3",
                "16.7",
                "10.9",
                "9.1",
                "18.2",
                "17.5",
                "23",
                "12.9",
                "9.3",
                "8.2",
                "4",
                "14.6",
                "19",
                "11.9",
                "13.5",
                "17.5",
                "11",
                "4.5"
            ],
            "type": "choropleth",
            "zauto": true,
            "name": "D"
        }
    ]
}


var gunLawScore = {
    "frames": [],
    "layout": {
        "showlegend": true,
        "title": "ANNUAL GUN LAW SCORECARD",
        "yaxis": {
            "range": [
                1.1406400878554788,
                24.691312935334686
            ],
            "type": "linear",
            "autorange": true,
            "title": "GUN DEATH RATE (PER 100K)"
        },
        "breakpoints": [],
        "shapes": [],
        "xaxis": {
            "range": [
                -3.8747449760414234,
                53.81964242371902
            ],
            "type": "linear",
            "autorange": true,
            "title": "GUN LAW STRENGTH (RANKED)"
        },
        "hovermode": "closest",
        "geo": {
            "showlakes": true,
            "scope": "usa",
            "lakecolor": "rgb(255, 255, 255)",
            "projection": {
                "scale": 0.9944701686732179,
                "type": "albers usa"
            },
            "center": {
                "lat": 38.02127524366123,
                "lon": -94.81627410884508
            }
        },
        "legend": {
            "y": -0.13089005235602094,
            "x": 0.6426663062808974
        }
    },
    "data": [
        {
            "autobinx": true,
            "uid": "57d063",
            "ysrc": "manuelamachado:8:247255",
            "xsrc": "manuelamachado:8:89ca42",
            "mode": "markers",
            "marker": {
                "colorsrc": "manuelamachado:8:998eee",
                "autocolorscale": false,
                "sizeref": 12.14,
                "colorscale": [
                    [
                        0,
                        "rgb(5, 10, 172)"
                    ],
                    [
                        0.35,
                        "rgb(106, 137, 247)"
                    ],
                    [
                        0.5,
                        "rgb(190, 190, 190)"
                    ],
                    [
                        0.6,
                        "rgb(220, 170, 132)"
                    ],
                    [
                        0.7,
                        "rgb(230, 145, 90)"
                    ],
                    [
                        1,
                        "rgb(178, 10, 28)"
                    ]
                ],
                "color": [
                    "8",
                    "1",
                    "26",
                    "32",
                    "21",
                    "5",
                    "13",
                    "32",
                    "25",
                    "43",
                    "24",
                    "29",
                    "48",
                    "16",
                    "4",
                    "20",
                    "23",
                    "6",
                    "36",
                    "2",
                    "17",
                    "42",
                    "50",
                    "27",
                    "10",
                    "15",
                    "10",
                    "3",
                    "39",
                    "18",
                    "12",
                    "47",
                    "14",
                    "48",
                    "22",
                    "11",
                    "19",
                    "29",
                    "32",
                    "44",
                    "27",
                    "31",
                    "35",
                    "9",
                    "46",
                    "37",
                    "37",
                    "40",
                    "45",
                    "41",
                    "7"
                ],
                "sizemode": "area",
                "cauto": true,
                "sizesrc": "manuelamachado:8:70c3c2",
                "cmax": 50,
                "cmin": 1,
                "size": [
                    "17556",
                    "16306",
                    "15029",
                    "13577",
                    "10244",
                    "9712",
                    "8929",
                    "8925",
                    "8739",
                    "8103",
                    "7626",
                    "6939",
                    "6631",
                    "6136",
                    "5981",
                    "5949",
                    "5852",
                    "5798",
                    "5471",
                    "5387",
                    "4787",
                    "4157",
                    "3599",
                    "3455",
                    "3434",
                    "3201",
                    "3195",
                    "3067",
                    "2842",
                    "2517",
                    "2408",
                    "2328",
                    "2286",
                    "2145",
                    "1952",
                    "1685",
                    "1651",
                    "1645",
                    "1575",
                    "1349",
                    "1072",
                    "964",
                    "907",
                    "895",
                    "661",
                    "638",
                    "573",
                    "544",
                    "494",
                    "472",
                    "289"
                ]
            },
            "textsrc": "manuelamachado:8:9ad0e4",
            "text": [
                "Illinois",
                "California",
                "Florida",
                "Texas",
                "Ohio",
                "New York",
                "Pennsylvania",
                "Georgia",
                "North Carolina",
                "Louisiana",
                "Tennessee",
                "South Carolina",
                "Missouri",
                "Michigan",
                "Massachusetts",
                "Virginia",
                "Indiana",
                "Maryland",
                "Alabama",
                "New Jersey",
                "Wisconsin",
                "Kentucky",
                "Mississippi",
                "Oklahoma",
                "Washington",
                "Colorado",
                "District of Columbia",
                "Connecticut",
                "Arkansas",
                "Iowa",
                "Minnesota",
                "Arizona",
                "Oregon",
                "Kansas",
                "Nevada",
                "Delaware",
                "Nebraska",
                "New Mexico",
                "West Virginia",
                "Alaska",
                "Utah",
                "New Hampshire",
                "Maine",
                "Rhode Island",
                "Idaho",
                "Montana",
                "North Dakota",
                "South Dakota",
                "Wyoming",
                "Vermont",
                "Hawaii"
            ],
            "y": [
                "11.6",
                "7.9",
                "12.6",
                "12.1",
                "12.9",
                "4.4",
                "11.9",
                "14.9",
                "13.6",
                "21.2",
                "17",
                "17.7",
                "18.8",
                "12.2",
                "3.4",
                "12",
                "14.9",
                "11.8",
                "21.4",
                "5.5",
                "11.4",
                "17.5",
                "19.8",
                "19.6",
                "9",
                "14.3",
                "9",
                "4.6",
                "17.7",
                "9.2",
                "7.6",
                "15.2",
                "11.8",
                "13.3",
                "16.7",
                "10.9",
                "9.1",
                "18.2",
                "17.5",
                "23",
                "12.9",
                "9.3",
                "8.2",
                "4",
                "14.6",
                "19",
                "11.9",
                "13.5",
                "17.5",
                "11",
                "4.5"
            ],
            "x": [
                "8",
                "1",
                "26",
                "32",
                "21",
                "5",
                "13",
                "32",
                "25",
                "43",
                "24",
                "29",
                "48",
                "16",
                "4",
                "20",
                "23",
                "6",
                "36",
                "2",
                "17",
                "42",
                "50",
                "27",
                "10",
                "15",
                "10",
                "3",
                "39",
                "18",
                "12",
                "47",
                "14",
                "48",
                "22",
                "11",
                "19",
                "29",
                "32",
                "44",
                "27",
                "31",
                "35",
                "9",
                "46",
                "37",
                "37",
                "40",
                "45",
                "41",
                "7"
            ],
            "autobiny": true,
            "type": "scatter",
            "name": "GUN VIOLENCE INCIDENTS (01/2013 - 03/2018)"
        }
    ]
}

var table = {
    "frames": [],
    "layout": {
        "autosize": true,
        "title": "50-STATE RANKINGS",
        "showlegend": true,
        "breakpoints": [],
        "shapes": [],
        "hovermode": false,
        "geo": {
            "showlakes": true,
            "scope": "usa",
            "lakecolor": "rgb(255, 255, 255)",
            "projection": {
                "scale": 0.9944701686732179,
                "type": "albers usa"
            },
            "center": {
                "lat": 38.02127524366123,
                "lon": -94.81627410884508
            }
        },
        "legend": {
            "y": -0.13089005235602094,
            "x": 0.6426663062808974,
            "orientation": "h"
        }
    },
    "data": [
        {
            "autobinx": true,
            "uid": "57d063",
            "cells": {
                "values": [
                    [
                        "GUN LAW STRENGTH (RANKED)",
                        "36",
                        "44",
                        "47",
                        "39",
                        "1",
                        "15",
                        "3",
                        "11",
                        "26",
                        "32",
                        "7",
                        "46",
                        "8",
                        "23",
                        "18",
                        "48",
                        "42",
                        "43",
                        "35",
                        "6",
                        "4",
                        "16",
                        "12",
                        "50",
                        "48",
                        "37",
                        "19",
                        "22",
                        "31",
                        "2",
                        "29",
                        "5",
                        "25",
                        "37",
                        "21",
                        "27",
                        "14",
                        "13",
                        "9",
                        "29",
                        "40",
                        "24",
                        "32",
                        "27",
                        "41",
                        "20",
                        "10",
                        "32",
                        "17",
                        "45"
                    ],
                    [
                        "STATE",
                        "Alabama",
                        "Alaska",
                        "Arizona",
                        "Arkansas",
                        "California",
                        "Colorado",
                        "Connecticut",
                        "Delaware",
                        "Florida",
                        "Georgia",
                        "Hawaii",
                        "Idaho",
                        "Illinois",
                        "Indiana",
                        "Iowa",
                        "Kansas",
                        "Kentucky",
                        "Louisiana",
                        "Maine",
                        "Maryland",
                        "Massachusetts",
                        "Michigan",
                        "Minnesota",
                        "Mississippi",
                        "Missouri",
                        "Montana",
                        "Nebraska",
                        "Nevada",
                        "New Hampshire",
                        "New Jersey",
                        "New Mexico",
                        "New York",
                        "North Carolina",
                        "North Dakota",
                        "Ohio",
                        "Oklahoma",
                        "Oregon",
                        "Pennsylvania",
                        "Rhode Island",
                        "South Carolina",
                        "South Dakota",
                        "Tennessee",
                        "Texas",
                        "Utah",
                        "Vermont",
                        "Virginia",
                        "Washington",
                        "West Virginia",
                        "Wisconsin",
                        "Wyoming"
                    ],
                    [
                        "2017 GRADE",
                        "F",
                        "F",
                        "F",
                        "F",
                        "A",
                        "C",
                        "A-",
                        "B",
                        "F",
                        "F",
                        "A-",
                        "F",
                        "B+",
                        "D-",
                        "C-",
                        "F",
                        "F",
                        "F",
                        "F",
                        "A-",
                        "A-",
                        "C",
                        "C+",
                        "F",
                        "F",
                        "F",
                        "D",
                        "D",
                        "F",
                        "A-",
                        "F",
                        "A-",
                        "D-",
                        "F",
                        "D",
                        "F",
                        "C",
                        "C",
                        "B+",
                        "F",
                        "F",
                        "D-",
                        "F",
                        "F",
                        "F",
                        "D",
                        "B",
                        "F",
                        "C-",
                        "F"
                    ],
                    [
                        "GUN DEATH RATE (RANKED)",
                        "2",
                        "1",
                        "16",
                        "9",
                        "43",
                        "20",
                        "46",
                        "37",
                        "26",
                        "17",
                        "47",
                        "19",
                        "34",
                        "18",
                        "39",
                        "23",
                        "13",
                        "3",
                        "42",
                        "32",
                        "50",
                        "27",
                        "44",
                        "4",
                        "7",
                        "6",
                        "40",
                        "15",
                        "38",
                        "45",
                        "8",
                        "48",
                        "21",
                        "30",
                        "25",
                        "5",
                        "33",
                        "31",
                        "49",
                        "10",
                        "22",
                        "14",
                        "28",
                        "24",
                        "36",
                        "29",
                        "41",
                        "12",
                        "35",
                        "11"
                    ],
                    [
                        "GUN DEATH RATE (PER 100K)",
                        "21.4",
                        "23",
                        "15.2",
                        "17.7",
                        "7.9",
                        "14.3",
                        "4.6",
                        "10.9",
                        "12.6",
                        "14.9",
                        "4.5",
                        "14.6",
                        "11.6",
                        "14.9",
                        "9.2",
                        "13.3",
                        "17.5",
                        "21.2",
                        "8.2",
                        "11.8",
                        "3.4",
                        "12.2",
                        "7.6",
                        "19.8",
                        "18.8",
                        "19",
                        "9.1",
                        "16.7",
                        "9.3",
                        "5.5",
                        "18.2",
                        "4.4",
                        "13.6",
                        "11.9",
                        "12.9",
                        "19.6",
                        "11.8",
                        "11.9",
                        "4",
                        "17.7",
                        "13.5",
                        "17",
                        "12.1",
                        "12.9",
                        "11",
                        "12",
                        "9",
                        "17.5",
                        "11.4",
                        "17.5"
                    ]
                ],
                "valuessrc": "manuelamachado:4:ff8160,777bbd,14cd54,238540,0bf8e1*",
                "fill": {}
            },
            "header": {
                "font": {
                    "color": [
                        [
                            "STATE",
                            "Alabama",
                            "Alaska",
                            "Arizona",
                            "Arkansas",
                            "California",
                            "Colorado",
                            "Connecticut",
                            "Delaware",
                            "Florida",
                            "Georgia",
                            "Hawaii",
                            "Idaho",
                            "Illinois",
                            "Indiana",
                            "Iowa",
                            "Kansas",
                            "Kentucky",
                            "Louisiana",
                            "Maine",
                            "Maryland",
                            "Massachusetts",
                            "Michigan",
                            "Minnesota",
                            "Mississippi",
                            "Missouri",
                            "Montana",
                            "Nebraska",
                            "Nevada",
                            "New Hampshire",
                            "New Jersey",
                            "New Mexico",
                            "New York",
                            "North Carolina",
                            "North Dakota",
                            "Ohio",
                            "Oklahoma",
                            "Oregon",
                            "Pennsylvania",
                            "Rhode Island",
                            "South Carolina",
                            "South Dakota",
                            "Tennessee",
                            "Texas",
                            "Utah",
                            "Vermont",
                            "Virginia",
                            "Washington",
                            "West Virginia",
                            "Wisconsin",
                            "Wyoming"
                        ]
                    ],
                    "colorsrc": "manuelamachado:4:777bbd*"
                },
                "fill": {
                    "color": [
                        [
                            "STATE",
                            "Alabama",
                            "Alaska",
                            "Arizona",
                            "Arkansas",
                            "California",
                            "Colorado",
                            "Connecticut",
                            "Delaware",
                            "Florida",
                            "Georgia",
                            "Hawaii",
                            "Idaho",
                            "Illinois",
                            "Indiana",
                            "Iowa",
                            "Kansas",
                            "Kentucky",
                            "Louisiana",
                            "Maine",
                            "Maryland",
                            "Massachusetts",
                            "Michigan",
                            "Minnesota",
                            "Mississippi",
                            "Missouri",
                            "Montana",
                            "Nebraska",
                            "Nevada",
                            "New Hampshire",
                            "New Jersey",
                            "New Mexico",
                            "New York",
                            "North Carolina",
                            "North Dakota",
                            "Ohio",
                            "Oklahoma",
                            "Oregon",
                            "Pennsylvania",
                            "Rhode Island",
                            "South Carolina",
                            "South Dakota",
                            "Tennessee",
                            "Texas",
                            "Utah",
                            "Vermont",
                            "Virginia",
                            "Washington",
                            "West Virginia",
                            "Wisconsin",
                            "Wyoming"
                        ]
                    ],
                    "colorsrc": "manuelamachado:4:777bbd*"
                }
            },
            "mode": "markers",
            "marker": {
                "autocolorscale": false,
                "sizeref": 12.14,
                "colorscale": [
                    [
                        0,
                        "rgb(5, 10, 172)"
                    ],
                    [
                        0.35,
                        "rgb(106, 137, 247)"
                    ],
                    [
                        0.5,
                        "rgb(190, 190, 190)"
                    ],
                    [
                        0.6,
                        "rgb(220, 170, 132)"
                    ],
                    [
                        0.7,
                        "rgb(230, 145, 90)"
                    ],
                    [
                        1,
                        "rgb(178, 10, 28)"
                    ]
                ],
                "sizemode": "area",
                "cauto": true,
                "cmax": 50,
                "cmin": 1
            },
            "autobiny": true,
            "type": "table",
            "name": "GUN VIOLENCE INCIDENTS (01/2013 - 03/2018)"
        }
    ]
}

var state = {
    "frames": [],
    "layout": {
        "title": "GUN DEATH RATE BY STATE (RANKED)",
        "geo": {
            "showlakes": true,
            "scope": "usa",
            "lakecolor": "rgb(255, 255, 255)",
            "projection": {
                "scale": 0.8160858762861624,
                "type": "albers usa"
            },
            "center": {
                "lat": 38.02429068199819,
                "lon": -83.89677521784496
            }
        },
        "breakpoints": []
    },
    "data": [
        {
            "reversescale": false,
            "locationssrc": "manuelamachado:6:7f069d",
            "zmax": 50,
            "uid": "93a716",
            "colorscale": [
                [
                    0,
                    "rgb(5, 10, 172)"
                ],
                [
                    0.35,
                    "rgb(106, 137, 247)"
                ],
                [
                    0.5,
                    "rgb(190, 190, 190)"
                ],
                [
                    0.6,
                    "rgb(220, 170, 132)"
                ],
                [
                    0.7,
                    "rgb(230, 145, 90)"
                ],
                [
                    1,
                    "rgb(178, 10, 28)"
                ]
            ],
            "zsrc": "manuelamachado:6:b7e8fe",
            "text": [
                "Illinois",
                "California",
                "Florida",
                "Texas",
                "Ohio",
                "New York",
                "Pennsylvania",
                "Georgia",
                "North Carolina",
                "Louisiana",
                "Tennessee",
                "South Carolina",
                "Missouri",
                "Michigan",
                "Massachusetts",
                "Virginia",
                "Indiana",
                "Maryland",
                "Alabama",
                "New Jersey",
                "Wisconsin",
                "Kentucky",
                "Mississippi",
                "Oklahoma",
                "Washington",
                "Colorado",
                "District of Columbia",
                "Connecticut",
                "Arkansas",
                "Iowa",
                "Minnesota",
                "Arizona",
                "Oregon",
                "Kansas",
                "Nevada",
                "Delaware",
                "Nebraska",
                "New Mexico",
                "West Virginia",
                "Alaska",
                "Utah",
                "New Hampshire",
                "Maine",
                "Rhode Island",
                "Idaho",
                "Montana",
                "North Dakota",
                "South Dakota",
                "Wyoming",
                "Vermont",
                "Hawaii"
            ],
            "zmin": 1,
            "locations": [
                "IL",
                "CA",
                "FL",
                "TX",
                "OH",
                "NY",
                "PA",
                "GA",
                "NC",
                "LA",
                "TN",
                "SC",
                "MO",
                "MI",
                "MA",
                "VA",
                "IN",
                "MD",
                "AL",
                "NJ",
                "WI",
                "KY",
                "MS",
                "OK",
                "WA",
                "CO",
                "DC",
                "CT",
                "AR",
                "IA",
                "MN",
                "AZ",
                "OR",
                "KS",
                "NV",
                "DE",
                "NE",
                "NM",
                "WV",
                "AK",
                "UT",
                "NH",
                "ME",
                "RI",
                "ID",
                "MT",
                "ND",
                "SD",
                "WY",
                "VT",
                "HI"
            ],
            "textsrc": "manuelamachado:6:dd3185",
            "autocolorscale": false,
            "colorbar": {
                "y": 0.5942408376963351,
                "x": 0.891825876662636,
                "title": "RANKING"
            },
            "showscale": true,
            "marker": {
                "line": {
                    "color": "rgb(255,255,255)",
                    "width": 2
                }
            },
            "locationmode": "USA-states",
            "z": [
                "34",
                "43",
                "26",
                "28",
                "25",
                "48",
                "31",
                "17",
                "21",
                "3",
                "14",
                "10",
                "7",
                "27",
                "50",
                "29",
                "18",
                "32",
                "2",
                "45",
                "35",
                "13",
                "4",
                "5",
                "41",
                "20",
                "41",
                "46",
                "9",
                "39",
                "44",
                "16",
                "33",
                "23",
                "15",
                "37",
                "40",
                "8",
                "12",
                "1",
                "24",
                "38",
                "42",
                "49",
                "19",
                "6",
                "30",
                "22",
                "11",
                "36",
                "47"
            ],
            "type": "choropleth",
            "zauto": true,
            "name": "E"
        }
    ]
}
